### ISSUE TITLE
Error handling suggestion?

### ISSUE THREAD

**Issue by delbinwen** [severb/flowy#17]
Hi,

We're trying AWS SWF and the package, flowy, you created is a big help. It made us easy to write our own logic and validate it. Good job!

Look at the source code, you intend to let developer to handle activity error/timeout; it's okay. We just want to know do you have any good suggestion to handle activity error with flowy, especially for activities running on parallel? For example, we have (same) 10 activities (with different input) running and we want to re-run failed ones if any.

I apologize if this is not the right place to get some help.

Thanks,
Wesley

**Comment by jinkuen** [comment]
Hello, 

As your example above, TaskError is raised because activity failed.
I try to implement subtask retry for sub-subtask failed, but I got SuspendTask, not TaskError.

Do you have any suggestion to implement subtask retry ?
Is it possible to get TaskError from sub-subtask failed ? 

Thanks.
