### ISSUE TITLE
How to get event type in decider ?

### ISSUE THREAD

**Issue by jinkuen** [severb/flowy#24]
Flowy is a good framework to work with swf without concerning event type.

Since I try to build a generic workflow (decider) with job description to generate different workflow easily.
I need to trace workflow/sub-workflow/activity status change during execution time.

Is any suggestion to get events like WorkflowExecutionStarted / WorkflowExecutionCompleted / ChildWorkflowExecutionFailed in decider ?

Thank you.

jinkuen

**Comment by severb** [comment]
You can't and shouldn't access events directly when using Flowy. Those are completely hidden from you. If you want to access the raw SWF responses you can use Boto.
