### ISSUE TITLE
How to get sub-workflow failed exception.

### ISSUE THREAD

**Issue by jinkuen** [severb/flowy#25]
Hello,

As your example in #17 , TaskError is raised because activity failed.
I try to implement subtask retry for sub-subtask failed, but I got SuspendTask, not TaskError.

Do you have any suggestion to implement subtask retry ?
Is it possible to get TaskError from sub-subtask failed ?

Thank you.

jinkuen

**Comment by severb** [comment]
Hello,

Yes, subworkflows should raise TaskError exceptions just like activities. Make sure you're not wrapping the subworkflow call itself in try-except but only the result() call:

Don't do this:
```python
try:
    r = self.subworkflow(...)  # this can raise SuspendTask
except TaskError:
    pass
```

Do this:

```python
r = self.subworkflow(...)
try:
    x = r.result()
except TaskError:
    pass
```
